services:
  exiftool:
    build: .
    ports:
      - "8050:8050"
    env_file:
      - ../.env
    environment:
      - ALLOWED_BASE=/mnt/barracuda/plex/Personal/Photos/Import-Staging
    volumes:
      - /mnt/barracuda/plex/Personal/Photos/Import-Staging:/mnt/barracuda/plex/Personal/Photos/Import-Staging
      - exiftool-data:/data

volumes:
  exiftool-data:
