services:
  exiftool:
    build: .
    ports:
      - "8051:8051"
    env_file:
      - ../.env
    environment:
      - ALLOWED_BASE=/mnt/barracuda/plex/Personal/Photos/Import-Staging
    volumes:
      - /mnt/barracuda/plex/Personal/Photos/Import-Staging:/mnt/barracuda/plex/Personal/Photos/Import-Staging
      - /home/media/plex_file_work/migration/copy_progress.db:/data/copy_progress.db
